In [12]:
#NumPy

import numpy as np

arr1 = np.arange(4, dtype = np.float_).reshape(2, 2)

print("First Array:\n", arr1)

arr2 = np.array([12, 12])
print("Second Array:\n", arr2)

print("Adding Array 1 with Array 2:")
print(np.add(arr1, arr2))

print("Subtracting Array 1 with Array 2:")
print(np.subtract(arr1, arr2))

print("Multiplying Array 1 and Array 2:")
print(np.multiply(arr1, arr2))

print("Dividing Array 1 from Array 2:")
print(np.divide(arr1, arr2))

print("Reciprocal of Array 2:\n", np.reciprocal(arr2))

First Array:
 [[0. 1.]
 [2. 3.]]
Second Array:
 [12 12]
Adding Array 1 with Array 2:
[[12. 13.]
 [14. 15.]]
Subtracting Array 1 with Array 2:
[[-12. -11.]
 [-10.  -9.]]
Multiplying Array 1 and Array 2:
[[ 0. 12.]
 [24. 36.]]
Dividing Array 1 from Array 2:
[[0.         0.08333333]
 [0.16666667 0.25      ]]
Reciprocal of Array 2:
 [0 0]


In [15]:
#Power function

import numpy as np

arr1 = np.array([5, 10, 15])

print("First Array is:\n", arr1)

print("After applying power function with 2:\n", np.power(arr1, 2))

arr2 = np.array([1, 2, 3])
print("\nSecond array is:\n", arr2)

print("Applying power function to Array 1 with power of Array 2:\n", np.power(arr1, arr2))

print("Mod() Function:\n", np.mod(arr1, arr2))

print("Remiander() function:\n", np.remainder(arr1, arr2))

First Array is:
 [ 5 10 15]
After applying power function with 2:
 [ 25 100 225]

Second array is:
 [1 2 3]
Applying power function to Array 1 with power of Array 2:
 [   5  100 3375]
Mod() Function:
 [0 0 0]
Remiander() function:
 [0 0 0]
